<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>CadBench</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Program.fs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aardvark.Application.Slim.Vulkan" Version="5.7.0-prerelease0003" />
    <PackageReference Include="Aardvark.PixImage.ImageSharp" Version="3.0.2" />
    <PackageReference Include="Aardvark.SceneGraph" Version="5.7.0-prerelease0003" />
  </ItemGroup>

</Project>
